version: '3.4'

services:
  erni.server:
    image: ${DOCKER_REGISTRY-}erniserver
    build:
      context: .
      dockerfile: ERNI.Server/Dockerfile
    depends_on:
      - postgres

  postgres:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=erni
    volumes:
      - ./volumes/data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
